# Generated by Django 3.0.7 on 2020-09-02 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='profilepic.jpg', null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('area', models.CharField(choices=[('Mantenimiento', 'Mantenimiento'), ('Producción', 'Producción'), ('Administrativo', 'Administrativo')], max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(choices=[('Molde', 'Molde'), ('Maquina', 'Maquina')], max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('En revisión', 'En revisión'), ('Abierta', 'Abierta'), ('Cerrada', 'Cerrada')], max_length=200, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('descripcion', models.CharField(max_length=1000, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='accounts.Customer')),
                ('equipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo', to='accounts.Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='TagEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordervideo', models.FileField(blank=True, null=True, upload_to='ordervideo/%Y/%m/%d/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_tags',
            field=models.ManyToManyField(to='accounts.TagOrder'),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderimages', models.ImageField(blank=True, null=True, upload_to='orderimages/%Y/%m/%d/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Order')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='tags',
            field=models.ManyToManyField(to='accounts.TagEquipment'),
        ),
    ]
