# Generated by Django 3.0.7 on 2020-08-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='asigned_to',
        ),
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(choices=[('En revisión', 'En revisión'), ('Abierta', 'Abierta'), ('Cerrada', 'Cerrada')], max_length=200, null=True),
        ),
    ]
