# Generated by Django 3.0.7 on 2020-07-21 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200720_2344'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='TagEquipment',
        ),
    ]
