# Generated by Django 3.0.7 on 2020-08-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200823_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='descripción',
            new_name='descripcion',
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
