# Generated by Django 3.0.7 on 2020-09-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_ordercomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('Molde', 'Molde'), ('Maquina', 'Maquina'), ('Periferico', 'Periferico')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='tags',
            field=models.ManyToManyField(blank=True, to='accounts.TagEquipment'),
        ),
    ]
