# Generated by Django 3.0.7 on 2020-07-27 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200726_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='area',
            field=models.CharField(choices=[('Mantenimiento', 'Mantenimiento'), ('Producción', 'Producción'), ('Administrativo', 'Administrativo')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='asigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to', to='accounts.Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='accounts.Customer'),
        ),
        migrations.DeleteModel(
            name='Representative',
        ),
    ]
