# Generated by Django 3.0.7 on 2020-07-27 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_order_date_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='asigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to', to='accounts.Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
